# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].strip('"').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cuspatial
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_GENERATOR
    - PARALLEL_LEVEL
    - SCCACHE_BUCKET
    - SCCACHE_IDLE_TIMEOUT
    - SCCACHE_REGION
    - SCCACHE_S3_KEY_PREFIX=cuspatial-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=cuspatial-linux64 # [linux64]
    - SCCACHE_S3_USE_SSL
    - SCCACHE_S3_NO_CREDENTIALS
  ignore_run_exports_from:
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }}
    {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    {% if cuda_major == "11" %}
    - {{ compiler('cuda11') }} ={{ cuda_version }}
    {% else %}
    - {{ compiler('cuda') }}
    {% endif %}
    - cuda-version ={{ cuda_version }}
    - ninja
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cuda-version ={{ cuda_version }}
    - cmake {{ cmake_version }}
    - cudf ={{ minor_version }}
    - cython >=3.0.0
    - libcuspatial ={{ version }}
    - python
    - rmm ={{ minor_version }}
    - scikit-build >=0.13.1
    - setuptools
  run:
    {% if cuda_major == "11" %}
    - cudatoolkit
    {% endif %}
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
    - cudf ={{ minor_version }}
    - geopandas >=0.11.0
    - python
    - rmm ={{ minor_version }}

test:            # [linux64]
  imports:       # [linux64]
    - cuspatial  # [linux64]

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: cuSpatial GPU Spatial and Trajectory Data Management and Analytics Library
