# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: cuspatial
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - VERSION_SUFFIX
    - CC
    - CXX
    - CUDAHOSTCXX

requirements:
  build:
    - python
    - cython >=0.29,<0.30
    - setuptools
    - cudf {{ minor_version }}.*
    - rmm {{ minor_version }}.*
    - libcuspatial {{ version }}.*
  run:
    - python
    - cudf {{ minor_version }}.*
    - rmm {{ minor_version }}.*
    - gdal >=3.2.0,<3.3.0a0
    - geopandas >=0.9.0,<0.10.0a0

test:
  commands:
    - python -c "import cuspatial"

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: cuSpatial GPU Spatial and Trajectory Data Management and Analytics Library

