# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: ${{ git.head_rev(".")[:8] }}

package:
  name: cuspatial
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  prefix_detection:
    # See https://github.com/rapidsai/build-planning/issues/160
    # Blanket ignore here as there are quite a few shared objects shipped in cuspatial
    ignore_binary_files: True
  script:
    content: |
      # Ignore conda-provided CMAKE_ARGS for the Python build.
      # unset CMAKE_ARGS

      # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
      # incrementing version number in the compile line doesn't break the
      # cache
      set -x
      export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
      export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
      set +x

      # This assumes the script is executed from the root of the repo directory
      ./build.sh cuspatial
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
      SCCACHE_S3_KEY_PREFIX: cuspatial/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}
requirements:
  build:
    - cmake ${{ cmake_version }}
    - ninja
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cuda-version =${{ cuda_version }}
    - ${{ stdlib("c") }}
  host:
    - cuda-version =${{ cuda_version }}
    - cudf =${{ minor_version }}
    - cython >=3.0.0
    - libcuspatial =${{ minor_version }}
    - pip
    - pylibcudf =${{ minor_version }}
    - python =${{ py_version }}
    - rapids-build-backend >=0.3.0,<0.4.0.dev0
    - rmm =${{ minor_version }}
    - scikit-build-core >=0.10.0
    - if: cuda_major != "11"
      then: cuda-cudart-dev
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - cudf =${{ minor_version }}
    - geopandas >=1.0.0
    - numpy >=1.23,<3.0a0
    - pylibcudf =${{ minor_version }}
    - python
    - rmm =${{ minor_version }}
    - if: cuda_major == "11"
      then: cudatoolkit
      else: cuda-cudart
  ignore_run_exports:
    by_name:
      - cuda-version
      - cuda-cudart
      - libcuspatial
      - if: cuda_major == "11"
        then: cudatoolkit

tests:
  - python:
      imports:
        - cuspatial
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cuspatial/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cuspatial/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cuspatial/pyproject.toml").project.description }}
