# Copyright (c) 2018, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ.get('CUDA', '11.5').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0

package:
  name: libcuspatial-split

source:
  git_url: ../../..

build:
  script_env:
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - PROJECT_FLASH
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libcuspatial-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libcuspatial-linux64 # [linux64]
    - SCCACHE_BUCKET=rapids-sccache
    - SCCACHE_REGION=us-west-2
    - SCCACHE_IDLE_TIMEOUT=32768

requirements:
  build:
    - cmake {{ cmake_version }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - libcudf {{ minor_version }}.*
    - librmm {{ minor_version }}.*
    - cudatoolkit {{ cuda_version }}.*
    - gdal {{ gdal_version }}

outputs:
  - name: libcuspatial
    version: {{ version }}
    script: install_libcuspatial.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      run_exports:
        - {{ pin_subpackage("libcuspatial", max_pin="x.x") }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - cudatoolkit {{ cuda_spec }}
        - libcudf {{ minor_version }}.*
        - librmm {{ minor_version }}.*
        - gdal {{ gdal_version }}
    test:
      commands:
        - test -f $PREFIX/lib/libcuspatial.so
    about:
      home: http://rapids.ai/
      license: Apache-2.0
      license_family: Apache
      license_file: LICENSE
      summary: libcuspatial library
  - name: libcuspatial-tests
    version: {{ version }}
    script: install_libcuspatial_tests.sh
    build:
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        - {{ compiler('cuda') }}
    requirements:
      build:
        - cmake {{ cmake_version }}
      run:
        - cudatoolkit {{ cuda_spec }}
        - gmock {{ gtest_version }}
        - gtest {{ gtest_version }}
        - {{ pin_subpackage('libcuspatial', exact=True) }}
